name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile
      
      - name: Run Release Script
        run: bun run release

      - name: Zip Release Artifacts
        run: bun run zip
      
      - name: Generate artifact attestation for MCP server binaries
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'packages/mcp-server/dist/*'

      - name: Get existing release body
        id: get_release
        uses: actions/github-script@v7
        with:
          script: |
            const release = await github.rest.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: ${{ github.event.release.id }}
            });
            return release.data.body || '';

      - name: Upload Release Artifacts
        env:
          GH_WORKFLOW_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EXISTING_BODY: ${{ steps.get_release.outputs.result }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitName: true
          artifacts: "packages/obsidian-plugin/releases/obsidian-plugin-*.zip,packages/obsidian-plugin/main.js,packages/obsidian-plugin/manifest.json,packages/obsidian-plugin/styles.css,packages/mcp-server/dist/*"
          body: |
            ${{ env.EXISTING_BODY }}

            ---
            ✨ This release includes attested build artifacts.
            📝 View attestation details in the [workflow run](${{ env.GH_WORKFLOW_URL }})