name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install --frozen-lockfile
      
      - name: Run Release Script
        run: bun run release

      - name: Zip Release Artifacts
        run: bun run zip
      
      - name: Generate artifact attestation for MCP server binaries
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: 'packages/mcp-server/dist/*'

      - name: Upload Release Artifacts
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBody: true
          omitName: true
          artifacts: "packages/obsidian-plugin/releases/obsidian-plugin-*.zip,packages/obsidian-plugin/main.js,packages/obsidian-plugin/manifest.json,packages/obsidian-plugin/styles.css,packages/mcp-server/dist/*"
